### ISSUE TITLE
Linear Regression in C++

### ISSUE THREAD

**Issue by yacineMahdid** [yacineMahdid/artificial-intelligence-and-machine-learning#34]
The first iteration I did kinda suck, also my tutorial on it is almost inaudible people are pissed off.
Should definitly try to fix that up!

## Subtasks:
- [ ] Read [this article to refresh my mind ](https://towardsdatascience.com/introduction-to-machine-learning-algorithms-linear-regression-14c4e325882a)
- [ ] Create a sample tutorial on FCC which will be about the implementation in C++
- [ ] Add a README.md to this algorithm that links to relevant resources
- [ ] Refactor the code so that it is more legible
- [ ] Add the information on the FCC tutorial with the code snippet
- [ ] Create a Pull Request and review your code
- [ ] Write the script for the tutorial
- [ ] Film the video with a walkthrough of the code
- [ ] Publish the code!
